### ISSUE TITLE
Clean up old events

### ISSUE THREAD

**Issue by not-a-feature** [fsi-tue/eei#11]
Old and unused events should be deleted for better maintenance.

**Comment by luoe** [comment]
I think it's better to just comment them. Unused duplicates could be deleted.

**Comment by luoe** [comment]
Event participation lists will be deleted automatically (introduced in c6ec67460b7b7828de74392c202da6a69ae895d1 and 937dd0d648fedd9ee3cf64471d18ef83214d6abc).
Old events should be reused in events_data.php.
