### ISSUE TITLE
Calendar files not generated

### ISSUE THREAD

**Issue by luoe** [fsi-tue/eei#125]
Since #102 was merged, the calendar download is empty.

For example: https://eei.fsi.uni-tuebingen.de/calender.php?e=WD3&lang=de&ics
there is no content sent by PHP, the content type is also 'text/html'.

Also pinging @am9zZWY since I can't assign him since he has just been invited to the fsi-tue orga by myself.

**Comment by am9zZWY** [comment]
This is because Wanderung 3 has no description with WD3 in the FSI cloud event
