### ISSUE TITLE
Update actions base image for pruning old event data

### ISSUE THREAD

**Issue by luoe** [fsi-tue/eei#143]
<img width="1108" alt="Bildschirmfoto 2024-03-31 um 15 15 19" src="https://github.com/fsi-tue/eei/assets/24625682/1140b10b-ab17-4751-b9d2-3050b1787663">

**Comment by am9zZWY** [comment]
Why don't we add Dependabot?

**Comment by luoe** [comment]
Thank you very much for the hint :) I'll implement it.
