### ISSUE TITLE
Feature Request: Add consistent timeline order for the dashboard

### ISSUE THREAD

**Issue by linususer** [fsi-tue/eei#165]
# Description
The dashboard currently has a weird timeline order: First the current events are displayed, then the future events are displayed and then afterwards the past events. In each category it is in itself weird ordered from the most past to the most recent past events. This is not very intuitive and kind of confusing as a user.

# Possible Solution
Change the current timeline order to a simple timeline from the most recent towards the most past events. 

# Screenshot
![image](https://github.com/fsi-tue/eei/assets/66415456/317bc40e-3c96-445f-9e84-7211295e3631)

**Comment by am9zZWY** [comment]
That's waaay too complicated to implement 😨
