### ISSUE TITLE
change the format of the participant list. "," instead of "("

### ISSUE THREAD

**Issue by SamuABC** [fsi-tue/eei#190]
## change the format of the participant list that gets send to the metas to csv format
from
 name (mail) studiengang, abschluss, semster
to
name, mail, studiengang, abschluss, semester

This makes it easier to import the data as a table into excel or libre office calc.
Because then you have the mails in an extra column and it is easier and faster to copy them into a mailing program. Otherwise I have to copy every single mail by hand (which isn't fun)

**Comment by am9zZWY** [comment]
Is it an option to just provide a list of mails in the mail?

**Comment by SamuABC** [comment]
An extra list of Mails does not help because I need "name, mail, studiengang, abschluss, semster" all in one row to have a proper table which I can use to assign the different groups in the pub crawl using the sorting feature. 
We can just leave it as it was and I replace the brackets with commas myself after recieving the mail. I just don't understand why we are using brackets instead of csv in the first place xD
