### ISSUE TITLE
Add english localisation

### ISSUE THREAD

**Issue by Pfonks** [fsi-tue/eei#73]
It could be useful to add functionality to switch localisations and add an english localisation

**Comment by PhictionalOne** [comment]
> Is the usage of an API like Google Translate or DeepL useful?

No. We want to keep it as lightweigt as possible, especially with no third party stuff. 

IMO a GET parameter `lang` and additional fields for the config should suffice. But this could be discussed.

**Comment by am9zZWY** [comment]
Maybe a transition to a `event_config.json` or `*.yaml` file could simplify the localisation
