### ISSUE TITLE
Currently missing service for sending out mails.

### ISSUE THREAD

**Issue by am9zZWY** [fsi-tue/eei#86]
Currently missing service for sending out mails.

_Originally posted by @Pfonks in https://github.com/fsi-tue/eei/pull/85#pullrequestreview-1382104487_

**Comment by am9zZWY** [comment]
Maybe use code from a project I wrote for my previous university: https://github.com/am9zZWY/kajak-verleih/blob/master/scripts/Email.php#L91

**Comment by am9zZWY** [comment]
Currently, `mail()` is used to send e-mails. For me as a dev, it's difficult because I have to change the `php.ini` in my local environment.
There are better solutions, such as `PHPMailer`, that allow to specify mail settings directly in the code.
What do you think?

**Comment by am9zZWY** [comment]
> I guess this issue should be fixed (as afaict the same changes that were introduced with the mmi codebase have been introduced here too).
> 
> Could you confirm that for me @am9zZWY ? If that is the case I will merge the waiting PRs #92 and #87

Well, that depends on the infrastructure of EEI. Is `composer` installed? I'm working on preparing #87. We need `composer` since it simplifies the way third-party software can be used. If `composer` is not there, I can try to manually add `PHPMailer` to the project

**Comment by Pfonks** [comment]
Composer is not installed on the system the eei is currently running on but either way I prefer adding PHPMailer directly (and if working, doing the same for the mmi - because it will probably be running on the same system the eei is curently running on).

**Comment by am9zZWY** [comment]
Okay, I'll take a look into that

**Comment by am9zZWY** [comment]
See #87
