### ISSUE TITLE
Sending mail not working

### ISSUE THREAD

**Issue by Pfonks** [fsi-tue/eei#95]
I've just tested it multiple times with different events. No mail is sent.

The .env file is created in the root directory and contains the information from #91 .

**Comment by Pfonks** [comment]
While debugging there is always a authentication failure for the SMTP connection, so it seems we can't get mail sending working without being able to authenticate.

This is a problem because to my knowledge we don't have any SMTP credentials for fsi@fsi

**Comment by am9zZWY** [comment]
It has to contain the information provided in the README.md

**Comment by am9zZWY** [comment]
https://github.com/fsi-tue/eei#setup
